/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Framep;

import Entity.PokemonEntity;

import Package.View;
import PaintPokemon.paintPicka;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author marti
 */
public class RegisterPokemon extends javax.swing.JFrame {

    /**
     * Creates new form RegisterPokemon
     */
    PokemonEntity vectorP[] = new PokemonEntity[6];
    PokemonEntity pickachu = null;
    public static int i = 0;
    ArrayList<PokemonEntity> pokebola = new ArrayList();

    public RegisterPokemon() {
        initComponents();
        this.setTitle("Arena de combate");
        this.setResizable(false);
        ImageIcon drednaw = new ImageIcon(getClass().getResource("/IconFrame/iconpokemon.png"));
        this.setIconImage(drednaw.getImage());
        BackgroundF b = new BackgroundF();
        this.add(b);
        this.setResizable(false);
        b.setBounds(0, 0, 650, 600);
        this.setTitle("Registrar Pokemon");
        this.setLocationRelativeTo(null);
        this.jTextField3nombre.setEditable(false);

    }

    public void deshabilitar() {
        this.jButton5pika.setEnabled(true);
        this.jButton4Gengar.setEnabled(true);
        this.jButton3bulbasur.setEnabled(true);
        this.jButton6darkrai.setEnabled(true);
        this.jButton7Drednaw.setEnabled(true);
        this.jButton8toricroak.setEnabled(true);
    }

    public void limpiar() {
        this.jTextField3nombre.setText("Por favor escoga un pokebola");
        this.jTextField1fila.setText("");
        this.jTextField2columna.setText("");
        this.jTextField4poder.setText("");
        this.jTextField5tipo.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1fila = new javax.swing.JTextField();
        jTextField2columna = new javax.swing.JTextField();
        jTextField3nombre = new javax.swing.JTextField();
        jTextField4poder = new javax.swing.JTextField();
        jTextField5tipo = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3bulbasur = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton4Gengar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton5pika = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton6darkrai = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton7Drednaw = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jButton8toricroak = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("REGISTRAR POKEMON ");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("Nombre :");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Fila :");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("Columna :");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setText("Poder : ");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("Tipo :");

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("Inicio");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1fila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1filaActionPerformed(evt);
            }
        });

        jTextField2columna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2columnaActionPerformed(evt);
            }
        });

        jTextField3nombre.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jTextField3nombre.setText("Por favor escoger un pokeball");
        jTextField3nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3nombreActionPerformed(evt);
            }
        });

        jTextField4poder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4poderActionPerformed(evt);
            }
        });

        jTextField5tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5tipoActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton2.setText("Registrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3bulbasur.setForeground(new java.awt.Color(255, 255, 255));
        jButton3bulbasur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesR/Bulbasurhuevo.png"))); // NOI18N
        jButton3bulbasur.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3bulbasur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3bulbasurMouseClicked(evt);
            }
        });
        jButton3bulbasur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3bulbasurActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("Pikachu");

        jButton4Gengar.setForeground(new java.awt.Color(255, 255, 255));
        jButton4Gengar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesR/SableyeHuevo.png"))); // NOI18N
        jButton4Gengar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4Gengar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4GengarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("Bulbasur");

        jButton5pika.setForeground(new java.awt.Color(255, 255, 255));
        jButton5pika.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesR/Pickahuevo.png"))); // NOI18N
        jButton5pika.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5pika.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5pikaMouseClicked(evt);
            }
        });
        jButton5pika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5pikaActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setText("Gengar");

        jButton6darkrai.setForeground(new java.awt.Color(255, 255, 255));
        jButton6darkrai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesR/darkhuevo.png"))); // NOI18N
        jButton6darkrai.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6darkrai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6darkraiMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setText("Darkrai");

        jButton7Drednaw.setForeground(new java.awt.Color(255, 255, 255));
        jButton7Drednaw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesR/drednawhuevo.png"))); // NOI18N
        jButton7Drednaw.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton7Drednaw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7DrednawMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel11.setText("Drednaw");

        jButton8toricroak.setForeground(new java.awt.Color(255, 255, 255));
        jButton8toricroak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagesR/toricroakhuevo.png"))); // NOI18N
        jButton8toricroak.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton8toricroak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8toricroakMouseClicked(evt);
            }
        });
        jButton8toricroak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8toricroakActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel12.setText("Toricroak");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(54, 54, 54)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11)
                                .addGap(51, 51, 51)
                                .addComponent(jLabel12)
                                .addGap(39, 39, 39))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel5)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jTextField2columna, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                                .addComponent(jTextField1fila)
                                                .addComponent(jTextField4poder))
                                            .addComponent(jTextField3nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jLabel7)
                                                .addGap(42, 42, 42))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(37, 37, 37)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jButton4Gengar)
                                                    .addComponent(jButton5pika)
                                                    .addComponent(jButton7Drednaw))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField5tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(137, 137, 137))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel9)
                                        .addGap(42, 42, 42)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton3bulbasur)
                                    .addComponent(jButton6darkrai)
                                    .addComponent(jButton8toricroak)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(jLabel8))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(jLabel10)))
                                .addContainerGap(25, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jTextField3nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jTextField1fila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton5pika)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField2columna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jTextField4poder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton6darkrai)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel10))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton4Gengar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel9))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButton3bulbasur)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton7Drednaw)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(jTextField5tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton8toricroak)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jButton1))
                    .addComponent(jLabel11))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1filaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1filaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1filaActionPerformed

    private void jTextField2columnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2columnaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2columnaActionPerformed

    private void jTextField3nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3nombreActionPerformed

    private void jTextField4poderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4poderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4poderActionPerformed

    private void jTextField5tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5tipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5tipoActionPerformed

//    public void PintarPicka(int x, int y) {
//        View v = new View();
//        v.setVisible(true);
//        JOptionPane.showMessageDialog(null, " Registrado exitoso ", " Mensaje", JOptionPane.INFORMATION_MESSAGE);
//        v.Pintarpicka(x, y);
//    }
//
//    public void PintarDrednaw() {
//        View v = new View();
//        v.setVisible(true);
//        JOptionPane.showMessageDialog(null, " Registrado exitoso ", " Mensaje", JOptionPane.INFORMATION_MESSAGE);
//        v.PintarDrednaw();
//    }
//
//    public void PintrBulbasur() {
//        View v = new View();
//        v.setVisible(true);
//        JOptionPane.showMessageDialog(null, " Registrado exitoso ", " Mensaje", JOptionPane.INFORMATION_MESSAGE);
//        v.Pintarbulba();
//    }
//
//    public void PintarDarkrai() {
//        View v = new View();
//        v.setVisible(true);
//        JOptionPane.showMessageDialog(null, " Registrado exitoso ", " Mensaje", JOptionPane.INFORMATION_MESSAGE);
//        v.PintarDarkrai();
//    }
//
//    public void PintarGengar() {
//        View v = new View();
//        v.setVisible(true);
//        JOptionPane.showMessageDialog(null, " Registrado exitoso ", " Mensaje", JOptionPane.INFORMATION_MESSAGE);
//        v.PintarGengar();
//    }
//
//    public void PintarToricroack() {
//        View v = new View();
//        v.setVisible(true);
//        JOptionPane.showMessageDialog(null, " Registrado exitoso ", " Mensaje", JOptionPane.INFORMATION_MESSAGE);
//        v.PintarToricroack();
//    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        PokemonEntity pickachu = null;
        int f = Integer.parseInt(this.jTextField2columna.getText());
        int c = Integer.parseInt(this.jTextField2columna.getText());
        if (this.jTextField1fila.getText().equals("") || this.jTextField2columna.getText().equals("")
                || this.jTextField4poder.getText().equals("") || this.jTextField5tipo.getText().equals("") || f > 5 || c > 5) {
            JOptionPane.showMessageDialog(null, " Por favor verifica ! ", "Alerta ", JOptionPane.WARNING_MESSAGE);
        } else {
            boolean bandera = false;
            if (this.jButton5pika.isEnabled() == false) {
                String nombre = this.jTextField3nombre.getText();
                String tipo = this.jTextField5tipo.getText();
                int fila = Integer.parseInt(this.jTextField1fila.getText());
                int columna = Integer.parseInt(this.jTextField2columna.getText());
                int poder = Integer.parseInt(this.jTextField4poder.getText());

                pickachu = new PokemonEntity(fila, columna, nombre, poder, tipo);
                for (int j = 0; j < i; j++) {
                    if (vectorP[j].getNombre().equalsIgnoreCase(nombre)) {
                        bandera = true;
                    }
                }
                if (bandera == true) {
                    JOptionPane.showMessageDialog(null, "El ´pokemon " + nombre + " ya esta registrado!", "Alerta ", JOptionPane.WARNING_MESSAGE);
                    limpiar();
                    deshabilitar();
                    bandera = false;
                } else {

                    vectorP[i] = pickachu;
                    i++;
                    JOptionPane.showMessageDialog(null, "Registro exitoso ", "Mensaje ", JOptionPane.INFORMATION_MESSAGE);
                    View v = new View();
                    v.LLenarvectorpokemon(fila, columna, nombre, poder, tipo);

                    limpiar();
                    deshabilitar();

                }

            } else {
                boolean bandera1 = false;
                if (this.jButton3bulbasur.isEnabled() == false) {
                    int x, y;
                    String nombre = this.jTextField3nombre.getText();
                    String tipo = this.jTextField5tipo.getText();
                    int fila = Integer.parseInt(this.jTextField1fila.getText());
                    int columna = Integer.parseInt(this.jTextField2columna.getText());
                    int poder = Integer.parseInt(this.jTextField4poder.getText());

                    pickachu = new PokemonEntity(fila, columna, nombre, poder, tipo);
                    for (int j = 0; j < i; j++) {
                        if (vectorP[j].getNombre().equalsIgnoreCase(nombre)) {
                            bandera1 = true;
                        }
                    }
                    if (bandera1 == true) {
                        JOptionPane.showMessageDialog(null, "El ´pokemon " + nombre + " ya esta registrado!", "Alerta ", JOptionPane.WARNING_MESSAGE);
                        limpiar();
                        deshabilitar();

                    } else {
                        vectorP[i] = pickachu;
                        i++;
                        JOptionPane.showMessageDialog(null, "Registro exitoso ", "Mensaje ", JOptionPane.INFORMATION_MESSAGE);
                        pokebola.add(pickachu);
                        View v = new View();
                        v.LLenarvectorpokemon(fila, columna, nombre, poder, tipo);
                        limpiar();
                        deshabilitar();

                    }
                }
                boolean bandera2 = false;
                if (this.jButton7Drednaw.isEnabled() == false) {
                    int x, y;
                    String nombre = this.jTextField3nombre.getText();
                    String tipo = this.jTextField5tipo.getText();
                    int fila = Integer.parseInt(this.jTextField1fila.getText());
                    int columna = Integer.parseInt(this.jTextField2columna.getText());
                    int poder = Integer.parseInt(this.jTextField4poder.getText());

                    pickachu = new PokemonEntity(fila, columna, nombre, poder, tipo);
                    for (int j = 0; j < i; j++) {
                        if (vectorP[j].getNombre().equalsIgnoreCase(nombre)) {
                            bandera2 = true;
                        }
                    }
                    if (bandera2 == true) {
                        JOptionPane.showMessageDialog(null, "El ´pokemon " + nombre + " ya esta registrado!", "Alerta ", JOptionPane.WARNING_MESSAGE);
                        limpiar();
                        deshabilitar();

                    } else {
                        vectorP[i] = pickachu;
                        i++;
                        JOptionPane.showMessageDialog(null, "Registro exitoso ", "Mensaje ", JOptionPane.INFORMATION_MESSAGE);
                        pokebola.add(pickachu);
                        View v = new View();
                        v.LLenarvectorpokemon(fila, columna, nombre, poder, tipo);
                        limpiar();
                        deshabilitar();

                    }
                }
                boolean bandera3 = false;
                if (this.jButton6darkrai.isEnabled() == false) {
                    int x, y;
                    String nombre = this.jTextField3nombre.getText();
                    String tipo = this.jTextField5tipo.getText();
                    int fila = Integer.parseInt(this.jTextField1fila.getText());
                    int columna = Integer.parseInt(this.jTextField2columna.getText());
                    int poder = Integer.parseInt(this.jTextField4poder.getText());

                    pickachu = new PokemonEntity(fila, columna, nombre, poder, tipo);

                    for (int j = 0; j < i; j++) {
                        if (vectorP[j].getNombre().equalsIgnoreCase(nombre)) {
                            bandera3 = true;
                        }
                    }
                    if (bandera3 == true) {
                        JOptionPane.showMessageDialog(null, "El ´pokemon " + nombre + " ya esta registrado!", "Alerta ", JOptionPane.WARNING_MESSAGE);
                        limpiar();
                        deshabilitar();

                    } else {
                        vectorP[i] = pickachu;
                        i++;
                        JOptionPane.showMessageDialog(null, "Registro exitoso ", "Mensaje ", JOptionPane.INFORMATION_MESSAGE);
                        pokebola.add(pickachu);
                        View v = new View();
                        v.LLenarvectorpokemon(fila, columna, nombre, poder, tipo);
                        limpiar();
                        deshabilitar();

                    }
                }
                boolean bandera4 = false;
                if (this.jButton4Gengar.isEnabled() == false) {
                    int x, y;
                    String nombre = this.jTextField3nombre.getText();
                    String tipo = this.jTextField5tipo.getText();
                    int fila = Integer.parseInt(this.jTextField1fila.getText());
                    int columna = Integer.parseInt(this.jTextField2columna.getText());
                    int poder = Integer.parseInt(this.jTextField4poder.getText());

                    pickachu = new PokemonEntity(fila, columna, nombre, poder, tipo);

                    for (int j = 0; j < i; j++) {
                        if (vectorP[j].getNombre().equalsIgnoreCase(nombre)) {
                            bandera4 = true;
                        }
                    }
                    if (bandera4 == true) {
                        JOptionPane.showMessageDialog(null, "El ´pokemon " + nombre + " ya esta registrado!", "Alerta ", JOptionPane.WARNING_MESSAGE);
                        limpiar();
                        deshabilitar();

                    } else {
                        vectorP[i] = pickachu;
                        i++;
                        JOptionPane.showMessageDialog(null, "Registro exitoso ", "Mensaje ", JOptionPane.INFORMATION_MESSAGE);
                        pokebola.add(pickachu);
                        View v = new View();
                        v.LLenarvectorpokemon(fila, columna, nombre, poder, tipo);
                        limpiar();
                        deshabilitar();

                    }
                }
                boolean bandera5 = false;
                if (this.jButton8toricroak.isEnabled() == false) {
                    int x, y;
                    String nombre = this.jTextField3nombre.getText();
                    String tipo = this.jTextField5tipo.getText();
                    int fila = Integer.parseInt(this.jTextField1fila.getText());
                    int columna = Integer.parseInt(this.jTextField2columna.getText());
                    int poder = Integer.parseInt(this.jTextField4poder.getText());

                    pickachu = new PokemonEntity(fila, columna, nombre, poder, tipo);

                    for (int j = 0; j < i; j++) {
                        if (vectorP[j].getNombre().equalsIgnoreCase(nombre)) {
                            bandera5 = true;
                        }
                    }
                    if (bandera5 == true) {
                        JOptionPane.showMessageDialog(null, "El ´pokemon " + nombre + " ya esta registrado!", "Alerta ", JOptionPane.WARNING_MESSAGE);
                        limpiar();
                        deshabilitar();

                    } else {
                        vectorP[i] = pickachu;
                        i++;
                        JOptionPane.showMessageDialog(null, "Registro exitoso ", "Mensaje ", JOptionPane.INFORMATION_MESSAGE);
                        pokebola.add(pickachu);
                        View v = new View();
                        v.LLenarvectorpokemon(fila, columna, nombre, poder, tipo);
                        limpiar();
                        deshabilitar();
                    }

                }
            }

        }
    }//GEN-LAST:event_jButton2ActionPerformed
//    public void revisar() {
    //        View v = new View();
    //        v.LLenarvectorpokemon();
    //        v.imprimir();
    //    }

    private void jButton5pikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5pikaActionPerformed
        this.jButton5pika.setEnabled(false);
        this.jTextField3nombre.setText("Pikachu");
        this.jTextField4poder.setText("20000");
        this.jTextField5tipo.setText("Electricidad estatica");
        this.jTextField4poder.setEnabled(false);
        this.jTextField5tipo.setEnabled(false);
    }//GEN-LAST:event_jButton5pikaActionPerformed

    private void jButton5pikaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5pikaMouseClicked


    }//GEN-LAST:event_jButton5pikaMouseClicked

    private void jButton3bulbasurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3bulbasurMouseClicked
        this.jButton3bulbasur.setEnabled(false);
        this.jTextField3nombre.setText("Bulbasur");
        this.jTextField4poder.setText("7000");
        this.jTextField5tipo.setText("Planta");
        this.jTextField4poder.setEnabled(false);
        this.jTextField5tipo.setEnabled(false);
    }//GEN-LAST:event_jButton3bulbasurMouseClicked

    private void jButton4GengarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4GengarActionPerformed
        this.jButton4Gengar.setEnabled(false);
        this.jTextField3nombre.setText("Gengar");
        this.jTextField4poder.setText("9000");
        this.jTextField5tipo.setText("Fantasma");
        this.jTextField4poder.setEnabled(false);
        this.jTextField5tipo.setEnabled(false);
    }//GEN-LAST:event_jButton4GengarActionPerformed

    private void jButton6darkraiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6darkraiMouseClicked
        this.jButton6darkrai.setEnabled(false);
        this.jTextField3nombre.setText("Darkrai");
        this.jTextField4poder.setText("10000");
        this.jTextField5tipo.setText("Oscuridad");
        this.jTextField4poder.setEnabled(false);
        this.jTextField5tipo.setEnabled(false);
    }//GEN-LAST:event_jButton6darkraiMouseClicked

    private void jButton7DrednawMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7DrednawMouseClicked
        this.jButton7Drednaw.setEnabled(false);
        this.jTextField3nombre.setText("Drednaw");
        this.jTextField4poder.setText("15000");
        this.jTextField5tipo.setText("Agua");
        this.jTextField4poder.setEnabled(false);
        this.jTextField5tipo.setEnabled(false);
    }//GEN-LAST:event_jButton7DrednawMouseClicked

    private void jButton8toricroakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8toricroakMouseClicked
        this.jButton8toricroak.setEnabled(false);
        this.jTextField3nombre.setText("Toricroak");
        this.jTextField4poder.setText("17000");
        this.jTextField5tipo.setText("Veneno");
        this.jTextField4poder.setEnabled(false);
        this.jTextField5tipo.setEnabled(false);

    }//GEN-LAST:event_jButton8toricroakMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        beginning v = new beginning();
        v.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton3bulbasurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3bulbasurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3bulbasurActionPerformed

    private void jButton8toricroakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8toricroakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8toricroakActionPerformed

//    @Override
//    public void paint(Graphics g) {
//        super.paint(g);
//        if (this.jButton5pika.getAction() != null) {
//            View v = new View();
//            this.setVisible(false);
//            v.setVisible(true);
//            ImageIcon pokemon = new ImageIcon(getClass().getResource("/Images/picka3.png"));
//            g.drawImage(pokemon.getImage(), 315, 470, 120, 120, this);
//            System.out.println("Entro a graphic");
//        }
//        ImageIcon pok2 = new ImageIcon(getClass().getResource("/Images/dar3.png"));
//        ImageIcon pok3 = new ImageIcon(getClass().getResource("/Images/gengar.png"));
//        ImageIcon pokemon = new ImageIcon(getClass().getResource("/Images/picka3.png"));
//        ImageIcon pok4 = new ImageIcon(getClass().getResource("/Images/drednaw.png"));
//        ImageIcon pok5 = new ImageIcon(getClass().getResource("/Images/bul3.png"));
//        ImageIcon pok6 = new ImageIcon(getClass().getResource("/Images/toricroak.png"));
//        ImageIcon ash = new ImageIcon(getClass().getResource("/Images/ash3.png"));
//        g.drawImage(ash.getImage(), 315, 270, 100, 100, this);
//        //(x,y)
//        g.drawImage(pokemon.getImage(), 315, 470, 120, 120, this); //fila 5 columna 2
//        g.drawImage(pok2.getImage(), 215, 50, 120, 120, this);//fila 4 columna 5
//        g.drawImage(pok3.getImage(), 515, 265, 115, 115, this);//fila 5 columna 6
//        g.drawImage(pok4.getImage(), 15, 470, 100, 100, this);//fila 2 columna 6
//        g.drawImage(pok5.getImage(), 15, 270, 95, 95, this);//fila 2 columna 4
//        g.drawImage(pok6.getImage(), 515, 50, 120, 120, this);//fila 2 columna 4 // el tamaño de este cambia porque es mas pequeño que los otros
//        // las x el primero es 15, segundo 150 , tercero 215, cuarto 315 , cinco 415 , sexto 515
//        // las y el primero es 50 , el segundo es 150 , tercero 270 , cuarto 370, quinto 450 y sexto 550
//        // entre el x es menor mas a la izquierda y mayor para la derecha
//        // entre el y es menor mas para arriba y mayor para abajo
    // para bul3 y drednaw en y el primero 70 , segundo 170 , tercero 270 , cuarto 370 , quinto 470 sexto en y es 570 
    //dar3 el primero es 50, segundo 150
    // }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterPokemon.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterPokemon.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterPokemon.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterPokemon.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterPokemon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3bulbasur;
    private javax.swing.JButton jButton4Gengar;
    private javax.swing.JButton jButton5pika;
    private javax.swing.JButton jButton6darkrai;
    private javax.swing.JButton jButton7Drednaw;
    private javax.swing.JButton jButton8toricroak;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JTextField jTextField1fila;
    public javax.swing.JTextField jTextField2columna;
    public javax.swing.JTextField jTextField3nombre;
    public javax.swing.JTextField jTextField4poder;
    public javax.swing.JTextField jTextField5tipo;
    // End of variables declaration//GEN-END:variables
}
